version: '3.8'

services:
    db:
        image: mariadb:latest
        environment:
            MYSQL_DATABASE: laravel_app
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
        ports:
            - "3307:3306"
        volumes:
            - ./db:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - "8082:80"
        depends_on:
            - db
        environment:
            MYSQL_ROOT_PASSWORD: root

    php:
        build:
            context: .
            dockerfile: ./Docker/php/Dockerfile
        depends_on:
            - db
        volumes:
            - .:/var/www/app

    web:
        build:
            context: .
            dockerfile: ./Docker/web/Dockerfile
        depends_on:
            - php
        ports:
            - "8001:8001"
        volumes:
            - .:/var/www/app

